version: '3.9'

services:
  radio-bot:
    build: .
    restart: always
    command: python bot/main.py
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache

  radio-worker:
    build: .
    restart: always
    command: python worker/stream_worker.py
    volumes:
      - ./data:/app/data
      - ./cache:/app/cache